---

- name: "update and upgrade packages." 
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: remove uneeded apps
  become: yes
  apt:
    autoremove: yes
- name: install deps 
  become: yes 
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes